c_stdlib_version:            # [osx]
  - "11.0"                   # [osx]

mpi:
  - mpich
  - openmpi
  - nompi

kokkos_arch:       # [linux]
  - None           # [linux]
  - VOLTA70        # [linux]
  - AMPERE80       # [linux]
  - AMPERE86       # [linux]
  - ADA89          # [linux]
  - HOPPER90       # [linux]
  # These require kokkos 4.7, LAMMPS is using 4.6
  # - BLACKWELL100   # [linux]
  # - BLACKWELL120   # [linux]


channel_targets:
  - metatensor main
