github:
  user_or_org: metatensor

github_actions:
  timeout_minutes: 1080
  triggers:
  - push
  - pull_request
  free_disk_space: [apt, cache, docker]

provider:
  linux_64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
  linux_aarch64: github_actions
